name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release bundle
        run: |
          mkdir -p dist
          zip -r dist/echoboot-${GITHUB_REF_NAME}.zip echoboot LICENSE README.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/echoboot-${{ github.ref_name }}.zip
